### ISSUE TITLE
Redefinition of type parameters are not included in the XML export

### ISSUE THREAD

**Issue by serefarikan** [openEHR/adl-tools#8]
The redefinition of type parameters such as `normal_range` for `DV_COUNT` having type `DV_INTERVAL<DV_COUNT>` instead of `DV_INTERVAL<DV_ORDERED>` is not included in the XML export of RM. 

see the following excerpt from an export of openEHR rm 1.0.2:

```
<class_definitions id="DV_COUNT">
  <name>DV_COUNT</name>
  <ancestors>DV_AMOUNT</ancestors>
  <properties id="magnitude">
   <name>magnitude</name>
   <type>Integer</type>
   <type_ref>
    <type>Integer</type>
   </type_ref>
   <is_mandatory>false</is_mandatory>
   <is_computed>false</is_computed>
   <is_im_infrastructure>false</is_im_infrastructure>
   <is_im_runtime>false</is_im_runtime>
  </properties>
  <source_schema_id>openehr_basic_types_1.0.2</source_schema_id>
  <is_abstract>false</is_abstract>
  <is_override>false</is_override>
  <uid>477</uid>
 </class_definitions>`
```

I don't know if this points at a limitation in the BMM but without having this information encoded in the RM export some way, code that uses the XML export cannot be aware of this redefinition.

**Comment by wolandscat** [comment]
The XML export is actually a correct representation of the [modern UML form of the RM](http://www.openehr.org/releases/RM/latest/docs/index), which doesn't include 'anchored types', an Eiffel concept that was shown in diagrams in the old 1.0.2 PDF specs, but doesn't exist in UML. So I'll close this but add an enhancement request to add anchored types to BMM.
